apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=          # "postgres" encoded in base64
  DB_PASS: eHVhbmhhaTIwMTA0MQ==  # "xuanhai201041" encoded in base64
  DB_NAME: U3R1ZGVudExpc3Q=      # "StudentList" encoded in base64
  DB_HOST: ZGI=                  # "db" encoded in base64
  DB_PORT: NTQzMg==              # "5432" encoded in base64
