apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-chart-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: api-chart
  endpoints:
  - port: http
    path: /api/metrics
    scheme: http
